add_subdirectory(core)
add_subdirectory(curve)
add_subdirectory(surface)
add_subdirectory(visualization)

if(OPENCAGD_ENABLE_EIGEN)
    add_subdirectory(linalg)
endif()
if(OPENCAGD_ENABLE_PLOT)
    add_subdirectory(plot)
endif()
if(OPENCAGD_ENABLE_VTK)
    add_subdirectory(vtk)
endif()
if(OPENCAGD_ENABLE_MPI)
    add_subdirectory(parallel)
endif()
