#pragma once

#if defined(_WIN32) || defined(__CYGWIN__)
  #define OPENCAGD_HELPER_DLL_IMPORT __declspec(dllimport)
  #define OPENCAGD_HELPER_DLL_EXPORT __declspec(dllexport)
#else
  #if defined(__GNUC__) && __GNUC__ >= 4
    #define OPENCAGD_HELPER_DLL_IMPORT __attribute__((visibility("default")))
    #define OPENCAGD_HELPER_DLL_EXPORT __attribute__((visibility("default")))
  #else
    #define OPENCAGD_HELPER_DLL_IMPORT
    #define OPENCAGD_HELPER_DLL_EXPORT
  #endif
#endif

#if defined(OPENCAGD_STATIC_DEFINE)
  #define OPENCAGD_CORE_API
  #define OPENCAGD_CURVE_API
  #define OPENCAGD_SURFACE_API
  #define OPENCAGD_LINALG_API
  #define OPENCAGD_VISUALIZATION_API
  #define OPENCAGD_PLOT_API
  #define OPENCAGD_VTK_API
  #define OPENCAGD_PARALLEL_API
#else
  #if defined(OPENCAGD_CORE_EXPORTS)
    #define OPENCAGD_CORE_API OPENCAGD_HELPER_DLL_EXPORT
  #else
    #define OPENCAGD_CORE_API OPENCAGD_HELPER_DLL_IMPORT
  #endif
  #if defined(OPENCAGD_CURVE_EXPORTS)
    #define OPENCAGD_CURVE_API OPENCAGD_HELPER_DLL_EXPORT
  #else
    #define OPENCAGD_CURVE_API OPENCAGD_HELPER_DLL_IMPORT
  #endif
  #if defined(OPENCAGD_SURFACE_EXPORTS)
    #define OPENCAGD_SURFACE_API OPENCAGD_HELPER_DLL_EXPORT
  #else
    #define OPENCAGD_SURFACE_API OPENCAGD_HELPER_DLL_IMPORT
  #endif
  #if defined(OPENCAGD_LINALG_EXPORTS)
    #define OPENCAGD_LINALG_API OPENCAGD_HELPER_DLL_EXPORT
  #else
    #define OPENCAGD_LINALG_API OPENCAGD_HELPER_DLL_IMPORT
  #endif
  #if defined(OPENCAGD_VISUALIZATION_EXPORTS)
    #define OPENCAGD_VISUALIZATION_API OPENCAGD_HELPER_DLL_EXPORT
  #else
    #define OPENCAGD_VISUALIZATION_API OPENCAGD_HELPER_DLL_IMPORT
  #endif
  #if defined(OPENCAGD_PLOT_EXPORTS)
    #define OPENCAGD_PLOT_API OPENCAGD_HELPER_DLL_EXPORT
  #else
    #define OPENCAGD_PLOT_API OPENCAGD_HELPER_DLL_IMPORT
  #endif
  #if defined(OPENCAGD_VTK_EXPORTS)
    #define OPENCAGD_VTK_API OPENCAGD_HELPER_DLL_EXPORT
  #else
    #define OPENCAGD_VTK_API OPENCAGD_HELPER_DLL_IMPORT
  #endif
  #if defined(OPENCAGD_PARALLEL_EXPORTS)
    #define OPENCAGD_PARALLEL_API OPENCAGD_HELPER_DLL_EXPORT
  #else
    #define OPENCAGD_PARALLEL_API OPENCAGD_HELPER_DLL_IMPORT
  #endif
#endif
